apiVersion: v1
kind: Service
metadata:
  name: online-course-big-model
  namespace: online-course
spec:
  ports:
    - nodePort: 30500
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: online-course-big-model
  sessionAffinity: None
  type: NodePort
